project_id = "sfxrvindaznnvliivhav"

[functions.generate-proposal]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.market-data-service]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false